version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: jambatu_wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: jambatu_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: '--max_allowed_packet=256M'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: jambatu_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - wordpress_network

volumes:
  wordpress_data:
    driver: local
  mysql_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge
